# Frozen-string-literal: true

source "https://rubygems.org"

# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve

# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem "jekyll-seo-tag", "~> 2.8"
  gem "jemoji", "~> 0.13"
end

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
platforms :mingw, :mswin, :x64_mingw_uc do
  gem "tzinfo", ">= 1", "< 3"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :mswin, :x64_mingw_uc]

# kramdown is now the default Markdown library for Jekyll.
# To use a custom Markdown library (like remark-math), you can use the `maruku` or `kramdown-math` plugins.
# See: https://github.com/jekyll/jekyll/issues/8499#issuecomment-769082763
gem "kramdown-parser-gfm"
